-- MySQL Script generated by MySQL Workbench
-- Sat Jun 28 20:20:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `id_proveedor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `piso` VARCHAR(45) NULL,
  `puerta` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gafas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gafas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gafas` (
  `id_gafas` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `graducacion_izq` INT NULL,
  `graducacion_dcha` INT NULL,
  `tipo_montura` ENUM('flotante', 'metalica', 'pasta') NULL,
  `color_montura` VARCHAR(45) NULL,
  `color_vidrio_dcha` VARCHAR(45) NULL,
  `color_vidrio_izq` VARCHAR(45) NULL,
  `precio` DECIMAL(5,2) NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_gafas`),
  INDEX `id_proveedor_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `id_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `mydb`.`Proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id_cliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `fecha_registro` DATE NULL,
  `id_recomendado_por` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `id_recomendado_por_idx` (`id_recomendado_por` ASC) VISIBLE,
  CONSTRAINT `id_recomendado_por`
    FOREIGN KEY (`id_recomendado_por`)
    REFERENCES `mydb`.`Cliente` (`id_cliente`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `id_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `id_ventas` INT NOT NULL,
  `fecha_venta` DATE NULL,
  `id_empleado` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_ventas`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`Empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cantidad_vendida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cantidad_vendida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cantidad_vendida` (
  `id_ventas` INT NOT NULL,
  `id_gafas` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_unitario` DECIMAL(5,2) NULL,
  `Cantidad_vendidacol` VARCHAR(45) NULL,
  INDEX `id_ventas_idx` (`id_ventas` ASC) VISIBLE,
  INDEX `id_gafas_idx` (`id_gafas` ASC) VISIBLE,
  CONSTRAINT `id_ventas`
    FOREIGN KEY (`id_ventas`)
    REFERENCES `mydb`.`Ventas` (`id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_gafas`
    FOREIGN KEY (`id_gafas`)
    REFERENCES `mydb`.`Gafas` (`id_gafas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
